name: CDK Nag Security Check

on:
  pull_request:
    paths:
      - 'cdk/**'
  push:
    branches:
      - main
    paths:
      - 'cdk/**'

jobs:
  cdk-nag-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cdk
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./cdk/package-lock.json
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
        
      - name: Run Tests
        run: npm test -- --passWithNoTests
      
      - name: Run CDK Synth with CDK Nag
        run: npx cdk synth
        env:
          AWS_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: dummy-key
          AWS_SECRET_ACCESS_KEY: dummy-secret
      
      - name: Check for CDK Nag warnings in CloudFormation template
        run: |
          # cdkコマンド実行結果を変数に格納
          CDK_OUTPUT=$(npx cdk synth 2>&1) || true
          
          # エラーと警告をカウント
          ERROR_COUNT=$(echo "$CDK_OUTPUT" | grep -c "\\[Error at" || echo 0)
          WARNING_COUNT=$(echo "$CDK_OUTPUT" | grep -c "\\[Warning at" || echo 0)
          
          echo "検出されたエラー: $ERROR_COUNT"
          echo "検出された警告: $WARNING_COUNT"
          
          # すべての警告とエラーを表示（存在する場合）
          echo "$CDK_OUTPUT" | grep -E "\\[(Error|Warning) at" || echo "警告・エラーは検出されませんでした"
          
          # エラーがあれば失敗、警告のみなら成功
          if [ "$ERROR_COUNT" -gt 0 ]; then
            echo "CDK Nagのチェックで$ERROR_COUNT件のエラーが検出されました！"
            exit 1
          else
            echo "CDK Nagのチェックに成功しました（警告: $WARNING_COUNT件）"
          fi
